using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using RevitMcpNext.Addin.Diagnostics;
using RevitMcpNext.Addin.Ipc;
using RevitMcpNext.Contracts;

namespace RevitMcpNext.Addin
{
    /// <summary>Per-op registry metadata (SPEC §4.1 OpMeta, Appendix B) for one key.</summary>
    internal sealed class OpMeta
    {
        public string Key { get; set; } = string.Empty;
        public string Tool { get; set; } = string.Empty;
        /// <summary>Discriminator value (null for tools without one).</summary>
        public string Op { get; set; }
        /// <summary>read | write | ui | lifecycle | control | code.</summary>
        public string Kind { get; set; } = "read";
        /// <summary>addin | broker | control | both.</summary>
        public string Impl { get; set; } = "addin";
        /// <summary>none | any | project | family | project_or_family.</summary>
        public string Scope { get; set; } = "none";
        public bool Ui { get; set; }
        public int Min { get; set; } = 2024;
        public bool Idle { get; set; } = true;
        /// <summary>none | in | own | temp | group | lifecycle.</summary>
        public string Tx { get; set; } = "none";
        public IReadOnlyList<string> Blast { get; set; } = new List<string>();
        public bool Strict { get; set; }
        /// <summary>never | auto | always.</summary>
        public string Job { get; set; } = "never";
        public bool Inproc { get; set; }
        public bool Cs { get; set; }
        /// <summary>True for dev./test. keys (metadata from OpAttribute, never checked against the catalog).</summary>
        public bool IsInternal { get; set; }

        public bool HasBlast(string rule) => Blast.Any(b => string.Equals(b, rule, StringComparison.Ordinal));

        public bool IsAddinBound => Impl == "addin" || Impl == "both";

        public static bool IsInternalKey(string key)
        {
            return key != null && (key.StartsWith("dev.", StringComparison.Ordinal) || key.StartsWith("test.", StringComparison.Ordinal));
        }

        internal static OpMeta FromWire(IDictionary<string, object> map)
        {
            var blast = new List<string>();
            IList<object> blastList = Wire.AsList(Wire.Get(map, "blast"));
            if (blastList != null) blast.AddRange(blastList.Where(item => item != null).Select(item => Convert.ToString(item, CultureInfo.InvariantCulture)));
            string key = Wire.GetString(map, "key") ?? string.Empty;
            return new OpMeta
            {
                Key = key,
                Tool = Wire.GetString(map, "tool") ?? key.Split('.')[0],
                Op = Wire.GetString(map, "op"),
                Kind = Wire.GetString(map, "kind") ?? "read",
                Impl = Wire.GetString(map, "impl") ?? "addin",
                Scope = Wire.GetString(map, "scope") ?? "none",
                Ui = Wire.GetBool(map, "ui") ?? false,
                Min = (int)(Wire.GetLong(map, "min") ?? 2024),
                Idle = Wire.GetBool(map, "idle") ?? false,
                Tx = Wire.GetString(map, "tx") ?? "none",
                Blast = blast,
                Strict = Wire.GetBool(map, "strict") ?? false,
                Job = Wire.GetString(map, "job") ?? "never",
                Inproc = Wire.GetBool(map, "inproc") ?? false,
                Cs = Wire.GetBool(map, "cs") ?? false
            };
        }

        internal static OpMeta FromAttribute(OpAttribute attribute)
        {
            string[] parts = attribute.Key.Split(new[] { '.' }, 2);
            return new OpMeta
            {
                Key = attribute.Key,
                Tool = parts[0],
                Op = parts.Length > 1 ? parts[1] : null,
                Kind = attribute.Kind ?? "read",
                Impl = "addin",
                Scope = attribute.Scope ?? "none",
                Ui = attribute.Ui,
                Min = attribute.Min,
                Idle = attribute.Idle,
                Tx = attribute.Tx ?? "none",
                Blast = (attribute.Blast ?? string.Empty).Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(b => b.Trim()).ToList(),
                Strict = attribute.Strict,
                Job = attribute.Job ?? "never",
                Inproc = attribute.Inproc,
                Cs = attribute.Cs,
                IsInternal = true
            };
        }
    }

    /// <summary>
    /// The tool catalog generated by contracts (artifacts/catalog/catalog.json, embedded as RevitMcpNext.catalog.json):
    /// {version, hash, tools, registry, errors, naming, protocol}. Only the registry, hash and tool discriminators are
    /// used by the add-in. Missing catalog → <see cref="Missing"/> (status reports CATALOG_MISSING).
    /// </summary>
    internal sealed class EmbeddedCatalog
    {
        public const string ResourceName = "RevitMcpNext.catalog.json";

        private EmbeddedCatalog()
        {
        }

        public bool Missing { get; private set; }
        public string Problem { get; private set; }
        public string Version { get; private set; } = string.Empty;
        public string Hash { get; private set; } = string.Empty;
        public IReadOnlyDictionary<string, OpMeta> Registry { get; private set; } = new Dictionary<string, OpMeta>(StringComparer.Ordinal);
        /// <summary>Discriminator arg per tool ("op", "kind", "check", "format"; null = none).</summary>
        public IReadOnlyDictionary<string, string> Discriminators { get; private set; } = new Dictionary<string, string>(StringComparer.Ordinal);

        public static EmbeddedCatalog Load(Assembly assembly)
        {
            try
            {
                using (Stream stream = assembly.GetManifestResourceStream(ResourceName))
                {
                    if (stream == null) return new EmbeddedCatalog { Missing = true, Problem = ErrorCodes.CatalogMissing };
                    using (var reader = new StreamReader(stream))
                    {
                        return Parse(reader.ReadToEnd());
                    }
                }
            }
            catch (Exception ex)
            {
                DiagnosticsLogger.Error("registry", "The embedded catalog could not be read.", ex);
                return new EmbeddedCatalog { Missing = true, Problem = ErrorCodes.CatalogMissing + ": " + ex.Message };
            }
        }

        public static EmbeddedCatalog Parse(string json)
        {
            var root = (IDictionary<string, object>)JsonWireCodec.DeserializeObject(json);
            var registry = new Dictionary<string, OpMeta>(StringComparer.Ordinal);
            IList<object> entries = Wire.AsList(Wire.Get(root, "registry")) ?? new List<object>();
            foreach (object entry in entries)
            {
                IDictionary<string, object> map = Wire.AsMap(entry);
                if (map == null) continue;
                OpMeta meta = OpMeta.FromWire(map);
                if (meta.Key.Length > 0) registry[meta.Key] = meta;
            }

            var discriminators = new Dictionary<string, string>(StringComparer.Ordinal);
            IList<object> tools = Wire.AsList(Wire.Get(root, "tools")) ?? new List<object>();
            foreach (object tool in tools)
            {
                IDictionary<string, object> map = Wire.AsMap(tool);
                string name = map == null ? null : Wire.GetString(map, "name");
                if (string.IsNullOrEmpty(name)) continue;
                discriminators[name] = Wire.GetString(map, "discriminator");
            }

            return new EmbeddedCatalog
            {
                Missing = registry.Count == 0,
                Problem = registry.Count == 0 ? ErrorCodes.CatalogMissing + ": the catalog has no registry entries" : null,
                Version = Wire.GetString(root, "version") ?? string.Empty,
                Hash = Wire.GetString(root, "hash") ?? string.Empty,
                Registry = registry,
                Discriminators = discriminators
            };
        }

        /// <summary>The discriminator arg of a tool (catalog first, then the fixed SPEC mapping).</summary>
        public string DiscriminatorOf(string tool)
        {
            if (string.IsNullOrEmpty(tool)) return null;
            if (Discriminators.TryGetValue(tool, out string fromCatalog)) return fromCatalog;
            switch (tool)
            {
                case "list": return "kind";
                case "check_model": return "check";
                case "export": return "format";
            }
            bool hasOps = Registry.Values.Any(meta => meta.Tool == tool && meta.Op != null);
            return hasOps ? "op" : null;
        }
    }

    /// <summary>A handler bound to a key.</summary>
    internal sealed class OpBinding
    {
        public string Key { get; set; } = string.Empty;
        public bool IsWildcard { get; set; }
        public MethodInfo Method { get; set; }
        public OpAttribute Attribute { get; set; }
        /// <summary>True for <c>static void X(ChangeContext c)</c> (run by the ChangeEngine).</summary>
        public bool UsesChangeContext { get; set; }
        public Func<RequestContext, OpResult> Invoke { get; set; }
        public Action<ChangeContext> InvokeChange { get; set; }

        public string Describe() => Method == null ? Key : Method.DeclaringType?.FullName + "." + Method.Name;
    }

    /// <summary>
    /// Reflects [Op] bindings once at startup, joins them with the embedded catalog and runs the both-way checks of
    /// SPEC §4.2: every catalog key with impl addin|both must be bound, and every bound key must be in the catalog
    /// (dev./test. keys excepted). Findings go to <see cref="Mismatches"/> (hello.capabilities.mismatches, status).
    /// </summary>
    internal sealed class OperationRegistry
    {
        private readonly Dictionary<string, OpBinding> _exact = new Dictionary<string, OpBinding>(StringComparer.Ordinal);
        private readonly Dictionary<string, OpBinding> _wildcards = new Dictionary<string, OpBinding>(StringComparer.Ordinal);
        private readonly Dictionary<string, OpMeta> _internal = new Dictionary<string, OpMeta>(StringComparer.Ordinal);
        private readonly List<string> _mismatches = new List<string>();

        private OperationRegistry(EmbeddedCatalog catalog)
        {
            Catalog = catalog;
        }

        public EmbeddedCatalog Catalog { get; }
        public bool CatalogMissing => Catalog.Missing;
        public string CatalogHash => Catalog.Hash;
        public IReadOnlyList<string> Mismatches => _mismatches;

        /// <summary>Builds the registry from the add-in assembly. test.* keys are kept only when <paramref name="includeTestOps"/>.</summary>
        public static OperationRegistry Build(Assembly assembly, EmbeddedCatalog catalog, bool includeTestOps)
        {
            var registry = new OperationRegistry(catalog ?? EmbeddedCatalog.Load(assembly));
            registry.Reflect(assembly, includeTestOps);
            registry.Check();
            DiagnosticsLogger.Info("registry", "Operation registry built: " + registry._exact.Count.ToString(CultureInfo.InvariantCulture) +
                " exact and " + registry._wildcards.Count.ToString(CultureInfo.InvariantCulture) + " wildcard bindings; catalog " +
                (registry.CatalogMissing ? "MISSING" : registry.Catalog.Registry.Count.ToString(CultureInfo.InvariantCulture) + " keys") + "; " +
                registry._mismatches.Count.ToString(CultureInfo.InvariantCulture) + " mismatch(es).",
                new Dictionary<string, object> { ["mismatches"] = registry._mismatches.ToList(), ["catalogHash"] = registry.CatalogHash });
            return registry;
        }

        /// <summary>Metadata for a key: the catalog entry, or the attribute metadata of an internal key.</summary>
        public OpMeta GetMeta(string key)
        {
            if (string.IsNullOrEmpty(key)) return null;
            if (Catalog.Registry.TryGetValue(key, out OpMeta meta)) return meta;
            return _internal.TryGetValue(key, out OpMeta internalMeta) ? internalMeta : null;
        }

        /// <summary>Finds the binding of a key (exact first, then the tool wildcard).</summary>
        public OpBinding GetBinding(string key)
        {
            if (string.IsNullOrEmpty(key)) return null;
            if (_exact.TryGetValue(key, out OpBinding binding)) return binding;
            int dot = key.IndexOf('.');
            string tool = dot < 0 ? key : key.Substring(0, dot);
            return _wildcards.TryGetValue(tool, out OpBinding wildcard) && !OpMeta.IsInternalKey(key) ? wildcard : null;
        }

        /// <summary>True when the key has metadata and a handler.</summary>
        public bool TryResolve(string key, out OpMeta meta, out OpBinding binding)
        {
            meta = GetMeta(key);
            binding = meta == null ? null : GetBinding(key);
            return meta != null && binding != null;
        }

        /// <summary>Registry keys with a handler (catalog keys bound exactly or by wildcard, plus internal keys).</summary>
        public List<string> BoundKeys()
        {
            var keys = new SortedSet<string>(StringComparer.Ordinal);
            foreach (OpMeta meta in Catalog.Registry.Values)
            {
                if (meta.IsAddinBound && GetBinding(meta.Key) != null) keys.Add(meta.Key);
            }
            foreach (string key in _internal.Keys) keys.Add(key);
            return keys.ToList();
        }

        public Capabilities Capabilities()
        {
            return new Capabilities { Keys = BoundKeys(), Mismatches = _mismatches.ToList() };
        }

        /// <summary>Keys of the same tool closest to <paramref name="key"/> (for UNKNOWN_OP details).</summary>
        public List<string> Closest(string key, int max = 5)
        {
            string tool = (key ?? string.Empty).Split('.')[0];
            IEnumerable<string> candidates = Catalog.Registry.Keys.Concat(_internal.Keys);
            List<string> sameTool = candidates.Where(k => k.Split('.')[0] == tool).ToList();
            if (sameTool.Count == 0) sameTool = candidates.ToList();
            return sameTool.OrderBy(k => ControlOperations.Levenshtein(k, key ?? string.Empty)).Take(max).ToList();
        }

        private void Reflect(Assembly assembly, bool includeTestOps)
        {
            Type[] types;
            try
            {
                types = assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                types = ex.Types.Where(type => type != null).ToArray();
                _mismatches.Add("TYPE_LOAD: " + string.Join("; ", ex.LoaderExceptions.Where(e => e != null).Select(e => e.Message).Distinct().Take(3)));
            }

            foreach (Type type in types)
            {
                MethodInfo[] methods;
                try
                {
                    methods = type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly);
                }
                catch
                {
                    continue;
                }
                foreach (MethodInfo method in methods)
                {
                    object[] attributes;
                    try
                    {
                        attributes = method.GetCustomAttributes(typeof(OpAttribute), false);
                    }
                    catch
                    {
                        continue;
                    }
                    foreach (OpAttribute attribute in attributes.OfType<OpAttribute>())
                    {
                        Bind(method, attribute, includeTestOps);
                    }
                }
            }
        }

        private void Bind(MethodInfo method, OpAttribute attribute, bool includeTestOps)
        {
            string key = (attribute.Key ?? string.Empty).Trim();
            string where = method.DeclaringType?.FullName + "." + method.Name;
            if (key.Length == 0)
            {
                _mismatches.Add("empty key on " + where);
                return;
            }
            if (key.StartsWith("test.", StringComparison.Ordinal) && !includeTestOps) return;

            OpBinding binding = CreateBinding(method, key, attribute, out string shapeProblem);
            if (binding == null)
            {
                _mismatches.Add("bad handler shape for " + key + " (" + where + "): " + shapeProblem);
                return;
            }

            if (key.EndsWith(".*", StringComparison.Ordinal))
            {
                string tool = key.Substring(0, key.Length - 2);
                binding.IsWildcard = true;
                if (_wildcards.ContainsKey(tool))
                {
                    _mismatches.Add("duplicate binding " + key + ": " + _wildcards[tool].Describe() + " and " + where);
                    return;
                }
                _wildcards[tool] = binding;
                return;
            }

            if (_exact.ContainsKey(key))
            {
                _mismatches.Add("duplicate binding " + key + ": " + _exact[key].Describe() + " and " + where);
                return;
            }
            _exact[key] = binding;
            if (OpMeta.IsInternalKey(key)) _internal[key] = OpMeta.FromAttribute(attribute);
        }

        private static OpBinding CreateBinding(MethodInfo method, string key, OpAttribute attribute, out string problem)
        {
            problem = null;
            ParameterInfo[] parameters = method.GetParameters();
            if (parameters.Length != 1)
            {
                problem = "expected one parameter (RequestContext or ChangeContext)";
                return null;
            }
            Type parameterType = parameters[0].ParameterType;
            if (parameterType == typeof(RequestContext) && method.ReturnType == typeof(OpResult))
            {
                var invoke = (Func<RequestContext, OpResult>)Delegate.CreateDelegate(typeof(Func<RequestContext, OpResult>), method);
                return new OpBinding { Key = key, Method = method, Attribute = attribute, Invoke = invoke };
            }
            if (parameterType == typeof(ChangeContext) && method.ReturnType == typeof(void))
            {
                var invoke = (Action<ChangeContext>)Delegate.CreateDelegate(typeof(Action<ChangeContext>), method);
                return new OpBinding { Key = key, Method = method, Attribute = attribute, UsesChangeContext = true, InvokeChange = invoke };
            }
            problem = "expected 'static OpResult X(RequestContext)' or 'static void X(ChangeContext)'";
            return null;
        }

        private void Check()
        {
            if (Catalog.Missing)
            {
                _mismatches.Insert(0, Catalog.Problem ?? ErrorCodes.CatalogMissing);
                return;
            }

            foreach (KeyValuePair<string, OpBinding> pair in _exact)
            {
                if (OpMeta.IsInternalKey(pair.Key)) continue;
                if (!Catalog.Registry.TryGetValue(pair.Key, out OpMeta meta))
                {
                    _mismatches.Add("unknown key " + pair.Key + " (bound by " + pair.Value.Describe() + ", not in the catalog)");
                    continue;
                }
                if (!meta.IsAddinBound)
                {
                    _mismatches.Add("bound key " + pair.Key + " has impl " + meta.Impl + " in the catalog");
                    continue;
                }
                CheckShape(meta, pair.Value);
            }

            foreach (KeyValuePair<string, OpBinding> pair in _wildcards)
            {
                List<OpMeta> covered = Catalog.Registry.Values.Where(meta => meta.Tool == pair.Key && meta.IsAddinBound).ToList();
                if (covered.Count == 0)
                {
                    _mismatches.Add("wildcard " + pair.Key + ".* matches no add-in key in the catalog");
                    continue;
                }
                foreach (OpMeta meta in covered.Where(meta => !_exact.ContainsKey(meta.Key))) CheckShape(meta, pair.Value);
            }

            foreach (OpMeta meta in Catalog.Registry.Values.OrderBy(meta => meta.Key, StringComparer.Ordinal))
            {
                if (meta.IsAddinBound && GetBinding(meta.Key) == null) _mismatches.Add("unbound " + meta.Key);
            }
        }

        private void CheckShape(OpMeta meta, OpBinding binding)
        {
            if (!binding.UsesChangeContext) return;
            bool engineKind = meta.Kind == RequestKinds.Write || (meta.Kind == RequestKinds.Ui && meta.Tx == "in");
            bool engineTx = meta.Tx == "in" || meta.Tx == "own" || meta.Tx == "none";
            if (!engineKind || !engineTx)
            {
                _mismatches.Add("ChangeContext handler for " + meta.Key + " but kind " + meta.Kind + " / tx " + meta.Tx + " is not run by the ChangeEngine");
            }
        }
    }
}
