using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using RevitMcpNext.Addin.Diagnostics;
using RevitMcpNext.Addin.Ipc;
using RevitMcpNext.Contracts;

namespace RevitMcpNext.Addin
{
    /// <summary>
    /// English names for built-in categories and parameters (SPEC §9.7), from the embedded
    /// Common/Aliases/aliases-&lt;year&gt;.json ({categories:{label:"OST_x"}, parameters:{label:["BIP",...]}}). The seed is
    /// hand-written (W1); P-READ replaces the files with tables generated by dev.dump_labels under /language ENU.
    /// </summary>
    internal static class EnglishAliases
    {
        private static readonly object Gate = new object();
        private static Dictionary<string, BuiltInCategory> _categoryByLabel;
        private static Dictionary<BuiltInCategory, string> _labelByCategory;
        private static Dictionary<string, List<BuiltInParameter>> _parametersByLabel;
        private static Dictionary<BuiltInParameter, string> _labelByParameter;

        /// <summary>English label → category (case-insensitive).</summary>
        public static bool TryCategory(string label, out BuiltInCategory category)
        {
            EnsureLoaded();
            category = BuiltInCategory.INVALID;
            if (string.IsNullOrWhiteSpace(label)) return false;
            return _categoryByLabel.TryGetValue(label.Trim(), out category);
        }

        /// <summary>The English label of a category, or null when the table has none.</summary>
        public static string LabelOf(BuiltInCategory category)
        {
            EnsureLoaded();
            return _labelByCategory.TryGetValue(category, out string label) ? label : null;
        }

        /// <summary>Built-in parameters carrying this English label (several for e.g. "Width"); empty when unknown.</summary>
        public static IReadOnlyList<BuiltInParameter> Parameters(string label)
        {
            EnsureLoaded();
            if (string.IsNullOrWhiteSpace(label)) return new List<BuiltInParameter>();
            return _parametersByLabel.TryGetValue(label.Trim(), out List<BuiltInParameter> list) ? list : new List<BuiltInParameter>();
        }

        /// <summary>The English label of a built-in parameter, or null.</summary>
        public static string LabelOf(BuiltInParameter parameter)
        {
            EnsureLoaded();
            return _labelByParameter.TryGetValue(parameter, out string label) ? label : null;
        }

        public static IEnumerable<string> CategoryLabels()
        {
            EnsureLoaded();
            return _categoryByLabel.Keys;
        }

        private static void EnsureLoaded()
        {
            if (_categoryByLabel != null) return;
            lock (Gate)
            {
                if (_categoryByLabel != null) return;
                var categoryByLabel = new Dictionary<string, BuiltInCategory>(StringComparer.OrdinalIgnoreCase);
                var labelByCategory = new Dictionary<BuiltInCategory, string>();
                var parametersByLabel = new Dictionary<string, List<BuiltInParameter>>(StringComparer.OrdinalIgnoreCase);
                var labelByParameter = new Dictionary<BuiltInParameter, string>();
                int year = McpRuntime.Instance?.Year ?? 2024;
                foreach (string name in new[] { "aliases-" + year.ToString(CultureInfo.InvariantCulture) + ".json", "aliases-2024.json", "aliases-2027.json" }.Distinct())
                {
                    try
                    {
                        string json = ReadResource("RevitMcpNext.Aliases." + name);
                        if (json == null) continue;
                        var root = JsonWireCodec.DeserializeObject(json) as IDictionary<string, object>;
                        if (root == null) continue;
                        foreach (KeyValuePair<string, object> pair in Wire.AsMap(Wire.Get(root, "categories")) ?? new Dictionary<string, object>())
                        {
                            string token = Convert.ToString(pair.Value, CultureInfo.InvariantCulture);
                            if (!Enum.TryParse(token, true, out BuiltInCategory category)) continue;
                            if (!categoryByLabel.ContainsKey(pair.Key)) categoryByLabel[pair.Key] = category;
                            if (!labelByCategory.ContainsKey(category)) labelByCategory[category] = pair.Key;
                        }
                        foreach (KeyValuePair<string, object> pair in Wire.AsMap(Wire.Get(root, "parameters")) ?? new Dictionary<string, object>())
                        {
                            IList<object> tokens = Wire.AsList(pair.Value) ?? new List<object> { pair.Value };
                            if (!parametersByLabel.TryGetValue(pair.Key, out List<BuiltInParameter> list))
                            {
                                list = new List<BuiltInParameter>();
                                parametersByLabel[pair.Key] = list;
                            }
                            foreach (object tokenValue in tokens)
                            {
                                string token = Convert.ToString(tokenValue, CultureInfo.InvariantCulture);
                                if (!Enum.TryParse(token, true, out BuiltInParameter parameter)) continue;
                                if (!list.Contains(parameter)) list.Add(parameter);
                                if (!labelByParameter.ContainsKey(parameter)) labelByParameter[parameter] = pair.Key;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        DiagnosticsLogger.Warn("aliases", "Could not load " + name + ": " + ex.Message);
                    }
                }
                _labelByCategory = labelByCategory;
                _parametersByLabel = parametersByLabel;
                _labelByParameter = labelByParameter;
                _categoryByLabel = categoryByLabel;
            }
        }

        private static string ReadResource(string name)
        {
            using (Stream stream = typeof(EnglishAliases).Assembly.GetManifestResourceStream(name))
            {
                if (stream == null) return null;
                using (var reader = new StreamReader(stream)) return reader.ReadToEnd();
            }
        }
    }

    /// <summary>
    /// Name/id resolution shared by all handlers (SPEC §9.5). Every miss throws NOT_FOUND (or AMBIGUOUS_NAME) with
    /// details {param, kind, value, candidates[]}, closest names first. Names compare case-insensitively.
    /// </summary>
    internal static class Resolve
    {
        // ---------------------------------------------------------------------------------------------------------
        // Categories
        // ---------------------------------------------------------------------------------------------------------

        /// <summary>
        /// English label (exact, then case-insensitive, then singular/plural), localized name (doc.Settings.Categories),
        /// then OST_ token or enum name.
        /// </summary>
        public static bool TryCategory(Document doc, string value, out BuiltInCategory category)
        {
            category = BuiltInCategory.INVALID;
            if (string.IsNullOrWhiteSpace(value)) return false;
            string text = value.Trim();
            if (EnglishAliases.TryCategory(text, out category)) return true;
            if (EnglishAliases.TryCategory(Plural(text), out category)) return true;
            if (text.EndsWith("s", StringComparison.OrdinalIgnoreCase) && EnglishAliases.TryCategory(text.Substring(0, text.Length - 1), out category)) return true;

            if (doc != null)
            {
                foreach (Category candidate in LocalizedCategories(doc))
                {
                    if (string.Equals(candidate.Name, text, StringComparison.OrdinalIgnoreCase))
                    {
                        category = SafeBuiltIn(candidate);
                        if (category != BuiltInCategory.INVALID) return true;
                    }
                }
            }

            string token = text.Replace(" ", string.Empty);
            if (Enum.TryParse(token, true, out category) && category != BuiltInCategory.INVALID && Enum.IsDefined(typeof(BuiltInCategory), category)) return true;
            if (Enum.TryParse("OST_" + token, true, out category) && Enum.IsDefined(typeof(BuiltInCategory), category)) return true;
            long? id = Wire.ToLong(text);
            if (id.HasValue && id.Value < 0 && Enum.IsDefined(typeof(BuiltInCategory), (int)id.Value))
            {
                category = (BuiltInCategory)(int)id.Value;
                return true;
            }
            category = BuiltInCategory.INVALID;
            return false;
        }

        public static BuiltInCategory CategoryId(Document doc, string value, string param = "category")
        {
            if (TryCategory(doc, value, out BuiltInCategory category)) return category;
            IEnumerable<string> names = EnglishAliases.CategoryLabels().Concat(LocalizedCategories(doc).Select(c => c.Name));
            throw OpException.NotFound(param, "category", value, Closest(value, names));
        }

        public static Category Category(Document doc, string value, string param = "category")
        {
            BuiltInCategory id = CategoryId(doc, value, param);
            Category category = null;
            try { category = Autodesk.Revit.DB.Category.GetCategory(doc, id); } catch { }
            if (category == null) throw OpException.NotFound(param, "category", value, new string[0]);
            return category;
        }

        public static List<BuiltInCategory> Categories(Document doc, IEnumerable<string> values, string param = "category")
        {
            return (values ?? Enumerable.Empty<string>()).Select(v => CategoryId(doc, v, param)).Distinct().ToList();
        }

        // ---------------------------------------------------------------------------------------------------------
        // Levels
        // ---------------------------------------------------------------------------------------------------------

        /// <summary>id | exact name | "active" (the active plan's level).</summary>
        public static Level Level(Document doc, string value, string param = "level", UIDocument uidoc = null)
        {
            string text = (value ?? string.Empty).Trim();
            if (text.Equals("active", StringComparison.OrdinalIgnoreCase))
            {
                View view = uidoc?.ActiveView ?? SafeActiveView(doc);
                Level level = view?.GenLevel;
                if (level != null) return level;
                throw new OpException(ErrorCodes.NotFound, "The active view has no level.", Details(param, "level", value, LevelNames(doc)));
            }
            List<Level> levels = new FilteredElementCollector(doc).OfClass(typeof(Autodesk.Revit.DB.Level)).Cast<Level>().ToList();
            Level byId = ById<Level>(doc, text);
            if (byId != null) return byId;
            return Single(levels, l => l.Name, text, param, "level");
        }

        /// <summary>The level at or below z (feet), else the lowest one; null when the document has no levels.</summary>
        public static Level NearestLevel(Document doc, double zFeet)
        {
            List<Level> levels = new FilteredElementCollector(doc).OfClass(typeof(Autodesk.Revit.DB.Level)).Cast<Level>()
                .OrderBy(l => l.ProjectElevation).ToList();
            if (levels.Count == 0) return null;
            Level below = levels.LastOrDefault(l => l.ProjectElevation <= zFeet + 1e-6);
            return below ?? levels[0];
        }

        /// <summary>The next level above <paramref name="level"/> (null when it is the highest).</summary>
        public static Level LevelAbove(Document doc, Level level)
        {
            return new FilteredElementCollector(doc).OfClass(typeof(Autodesk.Revit.DB.Level)).Cast<Level>()
                .Where(l => l.ProjectElevation > level.ProjectElevation + 1e-6)
                .OrderBy(l => l.ProjectElevation)
                .FirstOrDefault();
        }

        // ---------------------------------------------------------------------------------------------------------
        // Types
        // ---------------------------------------------------------------------------------------------------------

        /// <summary>id | "Family: Type" | "Type" (unique). <paramref name="category"/> narrows the candidates.</summary>
        public static T Type<T>(Document doc, string value, string param, BuiltInCategory? category = null) where T : ElementType
        {
            string text = (value ?? string.Empty).Trim();
            T byId = ById<T>(doc, text);
            if (byId != null) return byId;

            var collector = new FilteredElementCollector(doc).OfClass(typeof(T));
            if (category.HasValue) collector = collector.OfCategory(category.Value);
            List<T> types = collector.Cast<T>().ToList();
            if (typeof(T) == typeof(ElementType) || types.Count == 0)
            {
                var all = new FilteredElementCollector(doc).WhereElementIsElementType();
                if (category.HasValue) all = all.OfCategory(category.Value);
                types = all.OfType<T>().ToList();
            }

            int colon = text.IndexOf(':');
            if (colon > 0)
            {
                string family = text.Substring(0, colon).Trim();
                string typeName = text.Substring(colon + 1).Trim();
                List<T> exact = types.Where(t => Eq(t.FamilyName, family) && Eq(t.Name, typeName)).ToList();
                if (exact.Count == 1) return exact[0];
                if (exact.Count > 1) return exact[0];
            }

            List<T> byName = types.Where(t => Eq(t.Name, text)).ToList();
            if (byName.Count == 1) return byName[0];
            if (byName.Count > 1) throw OpException.Ambiguous(param, "type", value, byName.Select(FullTypeName));
            throw OpException.NotFound(param, "type", value, Closest(text, types.Select(FullTypeName)));
        }

        /// <summary>The document's default type for a category (or the first type of that category).</summary>
        public static T DefaultType<T>(Document doc, BuiltInCategory category) where T : ElementType
        {
            try
            {
                ElementTypeGroup? group = DefaultGroupOf(category);
                if (group.HasValue)
                {
                    ElementId id = doc.GetDefaultElementTypeId(group.Value);
                    if (id != null && id != ElementId.InvalidElementId && doc.GetElement(id) is T typed) return typed;
                }
                ElementId familyDefault = doc.GetDefaultFamilyTypeId(new ElementId(category));
                if (familyDefault != null && familyDefault != ElementId.InvalidElementId && doc.GetElement(familyDefault) is T familyTyped) return familyTyped;
            }
            catch
            {
                // Fall back to the first type.
            }
            return new FilteredElementCollector(doc).OfCategory(category).WhereElementIsElementType().OfType<T>().FirstOrDefault();
        }

        public static string FullTypeName(ElementType type)
        {
            if (type == null) return string.Empty;
            string family = type.FamilyName;
            return string.IsNullOrWhiteSpace(family) ? type.Name : family + ": " + type.Name;
        }

        // ---------------------------------------------------------------------------------------------------------
        // Views and sheets
        // ---------------------------------------------------------------------------------------------------------

        /// <summary>"active" | id | exact view name (non-templates first) | sheet number.</summary>
        public static View View(Document doc, string value, string param = "view", UIDocument uidoc = null)
        {
            string text = (value ?? string.Empty).Trim();
            if (text.Length == 0 || text.Equals("active", StringComparison.OrdinalIgnoreCase))
            {
                View active = uidoc?.ActiveView ?? SafeActiveView(doc);
                if (active != null) return active;
                throw new OpException(ErrorCodes.NotFound, "The document has no active view.", Details(param, "view", value, new string[0]));
            }
            View byId = ById<View>(doc, text);
            if (byId != null) return byId;

            List<View> views = new FilteredElementCollector(doc).OfClass(typeof(Autodesk.Revit.DB.View)).Cast<View>().ToList();
            List<View> named = views.Where(v => Eq(v.Name, text)).ToList();
            List<View> nonTemplates = named.Where(v => !v.IsTemplate).ToList();
            if (nonTemplates.Count == 1) return nonTemplates[0];
            if (nonTemplates.Count == 0 && named.Count == 1) return named[0];

            List<ViewSheet> sheets = views.OfType<ViewSheet>().Where(s => Eq(s.SheetNumber, text) || Eq(s.SheetNumber + " - " + s.Name, text)).ToList();
            if (sheets.Count == 1) return sheets[0];

            if (nonTemplates.Count > 1)
            {
                throw OpException.Ambiguous(param, "view", value, nonTemplates.Select(v => v.Name + " (" + v.ViewType + ", id " + v.Id.Value.ToString(CultureInfo.InvariantCulture) + ")"));
            }
            throw OpException.NotFound(param, "view", value, Closest(text, views.Where(v => !v.IsTemplate).Select(v => v.Name)));
        }

        /// <summary>id | sheet number | sheet name | "A101 - Name".</summary>
        public static ViewSheet Sheet(Document doc, string value, string param = "sheet")
        {
            string text = (value ?? string.Empty).Trim();
            ViewSheet byId = ById<ViewSheet>(doc, text);
            if (byId != null) return byId;
            List<ViewSheet> sheets = new FilteredElementCollector(doc).OfClass(typeof(ViewSheet)).Cast<ViewSheet>().ToList();
            ViewSheet byNumber = sheets.FirstOrDefault(s => Eq(s.SheetNumber, text) || Eq(s.SheetNumber + " - " + s.Name, text));
            if (byNumber != null) return byNumber;
            return Single(sheets, s => s.Name, text, param, "sheet", s => s.SheetNumber + " - " + s.Name);
        }

        // ---------------------------------------------------------------------------------------------------------
        // Materials, patterns, styles
        // ---------------------------------------------------------------------------------------------------------

        public static Material Material(Document doc, string value, string param = "material")
        {
            Material byId = ById<Material>(doc, value);
            if (byId != null) return byId;
            List<Material> materials = new FilteredElementCollector(doc).OfClass(typeof(Autodesk.Revit.DB.Material)).Cast<Material>().ToList();
            return Single(materials, m => m.Name, value, param, "material");
        }

        /// <summary>id | name | "solid" (the solid fill found by IsSolidFill), optionally limited to a target (Drafting/Model).</summary>
        public static FillPatternElement FillPattern(Document doc, string value, string param = "pattern", FillPatternTarget? target = null)
        {
            string text = (value ?? string.Empty).Trim();
            List<FillPatternElement> patterns = new FilteredElementCollector(doc).OfClass(typeof(FillPatternElement)).Cast<FillPatternElement>()
                .Where(p => !target.HasValue || SafePattern(p)?.Target == target.Value).ToList();
            if (text.Length == 0 || text.Equals("solid", StringComparison.OrdinalIgnoreCase) || text.Equals("solid fill", StringComparison.OrdinalIgnoreCase))
            {
                FillPatternElement solid = patterns.FirstOrDefault(p => SafePattern(p)?.IsSolidFill == true);
                if (solid != null) return solid;
            }
            FillPatternElement byId = ById<FillPatternElement>(doc, text);
            if (byId != null) return byId;
            return Single(patterns, p => p.Name, text, param, "fill pattern");
        }

        /// <summary>id | name | "solid" (the solid line pattern).</summary>
        public static ElementId LinePatternId(Document doc, string value, string param = "line_pattern")
        {
            string text = (value ?? string.Empty).Trim();
            if (text.Equals("solid", StringComparison.OrdinalIgnoreCase)) return LinePatternElement.GetSolidPatternId();
            LinePatternElement byId = ById<LinePatternElement>(doc, text);
            if (byId != null) return byId.Id;
            List<LinePatternElement> patterns = new FilteredElementCollector(doc).OfClass(typeof(LinePatternElement)).Cast<LinePatternElement>().ToList();
            return Single(patterns, p => p.Name, text, param, "line pattern").Id;
        }

        /// <summary>A line style (subcategory of Lines) by id or name.</summary>
        public static GraphicsStyle LineStyle(Document doc, string value, string param = "line_style")
        {
            string text = (value ?? string.Empty).Trim();
            GraphicsStyle byId = ById<GraphicsStyle>(doc, text);
            if (byId != null) return byId;
            Category lines = Autodesk.Revit.DB.Category.GetCategory(doc, BuiltInCategory.OST_Lines);
            var styles = new List<GraphicsStyle>();
            if (lines != null)
            {
                foreach (Category sub in lines.SubCategories)
                {
                    GraphicsStyle style = sub.GetGraphicsStyle(GraphicsStyleType.Projection);
                    if (style != null) styles.Add(style);
                }
            }
            return Single(styles, s => s.GraphicsStyleCategory?.Name ?? s.Name, text, param, "line style");
        }

        // ---------------------------------------------------------------------------------------------------------
        // Worksets, phases, design options, links
        // ---------------------------------------------------------------------------------------------------------

        public static Workset Workset(Document doc, string value, string param = "workset")
        {
            if (!doc.IsWorkshared) throw new OpException(ErrorCodes.NotFound, "'" + doc.Title + "' is not workshared, so it has no worksets.", Details(param, "workset", value, new string[0]));
            List<Workset> worksets = new FilteredWorksetCollector(doc).OfKind(WorksetKind.UserWorkset).ToList();
            long? id = Wire.ToLong(value);
            if (id.HasValue)
            {
                Workset byId = worksets.FirstOrDefault(w => w.Id.IntegerValue == id.Value);
                if (byId != null) return byId;
            }
            return Single(worksets, w => w.Name, value, param, "workset");
        }

        public static Phase Phase(Document doc, string value, string param = "phase")
        {
            Phase byId = ById<Phase>(doc, value);
            if (byId != null) return byId;
            List<Phase> phases = doc.Phases.Cast<Phase>().ToList();
            return Single(phases, p => p.Name, value, param, "phase");
        }

        public static DesignOption DesignOption(Document doc, string value, string param = "design_option")
        {
            DesignOption byId = ById<DesignOption>(doc, value);
            if (byId != null) return byId;
            List<DesignOption> options = new FilteredElementCollector(doc).OfClass(typeof(Autodesk.Revit.DB.DesignOption)).Cast<DesignOption>().ToList();
            return Single(options, o => o.Name, value, param, "design option");
        }

        /// <summary>A Revit link instance by id, instance name, type name or file name.</summary>
        public static RevitLinkInstance Link(Document doc, string value, string param = "link")
        {
            string text = (value ?? string.Empty).Trim();
            RevitLinkInstance byId = ById<RevitLinkInstance>(doc, text);
            if (byId != null) return byId;
            List<RevitLinkInstance> links = new FilteredElementCollector(doc).OfClass(typeof(RevitLinkInstance)).Cast<RevitLinkInstance>().ToList();
            List<RevitLinkInstance> matches = links.Where(l =>
                Eq(l.Name, text) || Eq(doc.GetElement(l.GetTypeId())?.Name, text) ||
                Eq(Path.GetFileNameWithoutExtension(doc.GetElement(l.GetTypeId())?.Name ?? string.Empty), Path.GetFileNameWithoutExtension(text)) ||
                (l.Name ?? string.Empty).StartsWith(text + " :", StringComparison.OrdinalIgnoreCase)).ToList();
            if (matches.Count == 1) return matches[0];
            if (matches.Count > 1) throw OpException.Ambiguous(param, "link", value, matches.Select(l => l.Name));
            throw OpException.NotFound(param, "link", value, Closest(text, links.Select(l => l.Name)));
        }

        // ---------------------------------------------------------------------------------------------------------
        // Elements
        // ---------------------------------------------------------------------------------------------------------

        /// <summary>
        /// Elements named by <paramref name="key"/>: numeric ids, UniqueIds, or "selection" (the registry's last UI
        /// selection of the doc; a stale selection adds notice SELECTION_STALE). Ids that no longer exist are skipped
        /// with warn IDS_GONE; when none remain, NOT_FOUND.
        /// </summary>
        public static List<Element> Elements(Document doc, PayloadReader args, string key, RequestContext ctx = null)
        {
            var tokens = new List<string>();
            List<long> ids = args.IdValues(key, tokens);
            var result = new List<Element>();
            var gone = new List<long>();
            var seen = new HashSet<long>();
            foreach (long id in ids)
            {
                Element element = SafeGet(doc, new ElementId(id));
                if (element == null) gone.Add(id);
                else if (seen.Add(element.Id.Value)) result.Add(element);
            }
            foreach (string token in tokens)
            {
                if (token.Equals("selection", StringComparison.OrdinalIgnoreCase))
                {
                    SelectionState selection = (ctx?.Registry ?? McpRuntime.Registry)?.GetSelection(doc) ?? new SelectionState();
                    if (!selection.IsActiveDoc && selection.AtUtc.HasValue)
                    {
                        ctx?.Notice(NoticeCodes.SelectionStale, "selection of '" + doc.Title + "' as of " + selection.AtUtc.Value.ToString("HH:mm:ss", CultureInfo.InvariantCulture) + " UTC (not the active document)");
                    }
                    foreach (long id in selection.Ids)
                    {
                        Element element = SafeGet(doc, new ElementId(id));
                        if (element != null && seen.Add(element.Id.Value)) result.Add(element);
                    }
                    continue;
                }
                Element byUnique = null;
                try { byUnique = doc.GetElement(token); } catch { }
                if (byUnique != null)
                {
                    if (seen.Add(byUnique.Id.Value)) result.Add(byUnique);
                }
                else
                {
                    throw OpException.NotFound(args.Field(key), "element", token, new string[0]);
                }
            }
            if (gone.Count > 0)
            {
                ctx?.Warn(WarningCodes.IdsGone, gone.Count.ToString(CultureInfo.InvariantCulture) + " id(s) no longer exist and were skipped", gone.Take(20));
            }
            if (result.Count == 0 && (ids.Count > 0 || tokens.Count > 0))
            {
                throw new OpException(ErrorCodes.NotFound, "None of the elements in " + args.Field(key) + " exist in '" + doc.Title + "'.",
                    Details(args.Field(key), "element", string.Join(",", ids.Take(10)), new string[0]));
            }
            return result;
        }

        public static Element SafeGet(Document doc, ElementId id)
        {
            try
            {
                return id == null || id == ElementId.InvalidElementId ? null : doc.GetElement(id);
            }
            catch
            {
                return null;
            }
        }

        /// <summary>The element with this numeric id when it is a T, else null (non-numeric text returns null).</summary>
        public static T ById<T>(Document doc, string value) where T : Element
        {
            long? id = Wire.ToLong(value?.Trim());
            if (!id.HasValue || doc == null) return null;
            return SafeGet(doc, new ElementId(id.Value)) as T;
        }

        // ---------------------------------------------------------------------------------------------------------
        // Generic name matching
        // ---------------------------------------------------------------------------------------------------------

        /// <summary>Exactly one item named <paramref name="value"/> (case-insensitive), else NOT_FOUND/AMBIGUOUS_NAME.</summary>
        public static T Single<T>(IEnumerable<T> items, Func<T, string> name, string value, string param, string kind, Func<T, string> describe = null)
        {
            List<T> list = items.ToList();
            string text = (value ?? string.Empty).Trim();
            List<T> exact = list.Where(item => string.Equals(name(item), text, StringComparison.Ordinal)).ToList();
            if (exact.Count == 1) return exact[0];
            List<T> matches = exact.Count > 1 ? exact : list.Where(item => Eq(name(item), text)).ToList();
            if (matches.Count == 1) return matches[0];
            Func<T, string> label = describe ?? name;
            if (matches.Count > 1) throw OpException.Ambiguous(param, kind, value, matches.Select(label));
            throw OpException.NotFound(param, kind, value, Closest(text, list.Select(label)));
        }

        /// <summary>Up to <paramref name="max"/> names closest to <paramref name="value"/> (prefix/contains first, then edit distance).</summary>
        public static List<string> Closest(string value, IEnumerable<string> names, int max = 8)
        {
            string text = (value ?? string.Empty).Trim();
            return (names ?? Enumerable.Empty<string>())
                .Where(n => !string.IsNullOrWhiteSpace(n))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(n => n.StartsWith(text, StringComparison.OrdinalIgnoreCase) ? 0 : n.IndexOf(text, StringComparison.OrdinalIgnoreCase) >= 0 ? 1 : 2)
                .ThenBy(n => ControlOperations.Levenshtein(n, text))
                .Take(max)
                .ToList();
        }

        public static bool Eq(string left, string right)
        {
            return string.Equals((left ?? string.Empty).Trim(), (right ?? string.Empty).Trim(), StringComparison.OrdinalIgnoreCase);
        }

        private static Dictionary<string, object> Details(string param, string kind, string value, IEnumerable<string> candidates)
        {
            return new Dictionary<string, object>
            {
                ["param"] = param,
                ["kind"] = kind,
                ["value"] = value,
                ["candidates"] = (candidates ?? Enumerable.Empty<string>()).ToList()
            };
        }

        private static IEnumerable<string> LevelNames(Document doc)
        {
            return new FilteredElementCollector(doc).OfClass(typeof(Autodesk.Revit.DB.Level)).Cast<Level>().Select(l => l.Name);
        }

        private static IEnumerable<Category> LocalizedCategories(Document doc)
        {
            if (doc == null) yield break;
            Categories categories;
            try { categories = doc.Settings.Categories; } catch { yield break; }
            foreach (Category category in categories) yield return category;
        }

        internal static BuiltInCategory SafeBuiltIn(Category category)
        {
            try
            {
                return category == null ? BuiltInCategory.INVALID : category.BuiltInCategory;
            }
            catch
            {
                return BuiltInCategory.INVALID;
            }
        }

        private static FillPattern SafePattern(FillPatternElement element)
        {
            try { return element?.GetFillPattern(); } catch { return null; }
        }

        private static View SafeActiveView(Document doc)
        {
            try { return doc?.ActiveView; } catch { return null; }
        }

        private static string Plural(string text)
        {
            if (text.EndsWith("y", StringComparison.OrdinalIgnoreCase)) return text.Substring(0, text.Length - 1) + "ies";
            return text.EndsWith("s", StringComparison.OrdinalIgnoreCase) ? text : text + "s";
        }

        private static ElementTypeGroup? DefaultGroupOf(BuiltInCategory category)
        {
            switch (category)
            {
                case BuiltInCategory.OST_Walls: return ElementTypeGroup.WallType;
                case BuiltInCategory.OST_Floors: return ElementTypeGroup.FloorType;
                case BuiltInCategory.OST_Roofs: return ElementTypeGroup.RoofType;
                case BuiltInCategory.OST_Ceilings: return ElementTypeGroup.CeilingType;
                case BuiltInCategory.OST_Grids: return ElementTypeGroup.GridType;
                case BuiltInCategory.OST_Levels: return ElementTypeGroup.LevelType;
                case BuiltInCategory.OST_Stairs: return ElementTypeGroup.StairsType;
                case BuiltInCategory.OST_StairsRailing: return ElementTypeGroup.StairsRailingType;
                case BuiltInCategory.OST_TextNotes: return ElementTypeGroup.TextNoteType;
                case BuiltInCategory.OST_Dimensions: return ElementTypeGroup.LinearDimensionType;
                case BuiltInCategory.OST_PipeCurves: return ElementTypeGroup.PipeType;
                case BuiltInCategory.OST_DuctCurves: return ElementTypeGroup.DuctType;
                case BuiltInCategory.OST_Conduit: return ElementTypeGroup.ConduitType;
                case BuiltInCategory.OST_CableTray: return ElementTypeGroup.CableTrayType;
                case BuiltInCategory.OST_FlexPipeCurves: return ElementTypeGroup.FlexPipeType;
                case BuiltInCategory.OST_FlexDuctCurves: return ElementTypeGroup.FlexDuctType;
                case BuiltInCategory.OST_Viewports: return ElementTypeGroup.ViewportType;
                default: return null;
            }
        }
    }
}
