// Catalog entry for `create_elements` (SPEC Appendix A/B). The advertised part must stay equal to docs/design/SPEC-catalog.mjs
// unless the lead approves a surface change (e2e/budgets.json baseline). Lanes extend examples, help and errors.
import { B, deg, E, I, LOOPS, meta, mm, N, op, P, PT, PTS, S, syn, W, WRITE, WRITE_TAIL } from "../params.js";
import type { ToolSpec } from "../types.js";

const M = meta(WRITE, { blast: ["create"] });

export const tool: ToolSpec = {
  name: "create_elements",
  title: "Create elements",
  description: "Create levels, grids, walls, floors, roofs, ceilings, rooms, areas, separators, openings, shafts, ref planes, model lines, stairs, railings, curtain grids, toposolids. mm; applies now, returns ids and undo.",
  group: "write",
  annotations: W,
  discriminator: "op",
  profiles: ["core", "full"],
  properties: {
    level: S("Base level name or id."),
    top: S("Top level (wall top constraint, shaft, stairs)."),
    elevation: mm(N("Level elevation mm.")),
    name: P.name,
    number: S("Room/area number."),
    department: S("Room department."),
    plans: B("level: also create floor and ceiling plans. Default true."),
    count: I("level/grid: how many to create. Default 1."),
    spacing: mm(N("level/grid: distance between copies mm; curtain_grid: grid spacing.")),
    start: P.start,
    end: P.end,
    through: mm(PT("Point on the arc: makes an arc (single segment).")),
    points: mm(PTS("[[x,y],...] mm: wall path, outline, stair path; toposolid [x,y,z] (z above level if set, else absolute).")),
    profile: mm(PTS("roof_extrusion: profile [[s,z],...] mm; s along start->end, z above level.")),
    holes: mm(LOOPS("Inner loops [[[x,y],...],...].")),
    closed: B("Close the loop back to the first point."),
    from: S("floor/ceiling: follow room boundaries: r# handle or 'selection' of rooms."),
    type: P.type,
    height: mm(N("wall: unconnected height mm when no top (default 3000); opening: opening height mm.")),
    offset: mm(N("Height above level mm (wall opening: sill height). Default 0.")),
    top_offset: mm(N("Offset from top level mm.")),
    line: syn(E(["center","core_center","finish_ext","finish_int","core_ext","core_int"], "wall location line. Default center."), {"centerline":"center","wallcenterline":"center","corecenterline":"core_center","finishexterior":"finish_ext","finishinterior":"finish_int","coreexterior":"core_ext","coreinterior":"core_int","exterior":"finish_ext","interior":"finish_int"}),
    structural: B("Structural wall/floor."),
    flip: B("wall: flip orientation."),
    slope: deg(N("Degrees (floor, roof).")),
    slope_edges: {"type":"array","items":{"type":"integer"},"description":"roof: edge indexes that slope. Default all when slope set."},
    overhang: mm(N("roof: overhang mm.")),
    depth: mm(N("roof_extrusion: extrusion length mm (left of start->end).")),
    at: P.at,
    all: B("room: place rooms in every enclosed area of the level."),
    allow_duplicate: B("room: allow a duplicate number."),
    view: S("Plan view (separators, areas, ref plane)."),
    host: S("Host id: wall/floor/roof/ceiling (opening), stairs (railing), curtain wall (curtain_grid)."),
    width: mm(N("stairs: run width mm.")),
    risers: I("stairs: riser count. Default from height."),
    direction: syn(E(["vertical","horizontal"], "curtain_grid: direction of the new grid lines."), {"vert":"vertical","horiz":"horizontal"}),
    positions: mm(PT("curtain_grid: offsets mm from the wall start (vertical) or base (horizontal).")),
    mullion: S("curtain_grid: mullion type to add on new lines."),
    line_style: S("Line style name."),
    survey: mm(PTS("toposolid: extra [[x,y,z]] points inside the outline.")),
    ...WRITE_TAIL,
  },
  required: ["op"],
  ops: {
    level: op("elevation", "name,plans,count,spacing", M, [{"op":"level","elevation":3500,"count":4,"spacing":3500}]),
    grid: op("start,end", "through,name,count,spacing", M, [{"op":"grid","start":[0,0],"end":[0,30000],"name":"1","count":6,"spacing":6000}]),
    wall: op("level,points/start+end", "type,height,top,offset,top_offset,line,structural,flip,closed,through", M, [{"op":"wall","level":"Level 1","points":[[0,0],[12000,0],[12000,8000],[0,8000]],"closed":true,"type":"Generic - 200mm","top":"Level 2"}, {"op":"wall","level":"Level 1","start":[0,0],"end":[6000,0],"height":3000}], { help: "One wall per segment of points (or start/end); closed adds the last segment. Height: top level + top_offset, else height (default 3000)." }),
    floor: op("level,points/from", "type,holes,offset,slope,structural", M, [{"op":"floor","level":"Level 1","points":[[0,0],[12000,0],[12000,8000],[0,8000]],"type":"Generic 300mm"}]),
    roof: op("level,points", "type,slope,slope_edges,overhang,offset", M, [{"op":"roof","level":"Level 2","points":[[0,0],[12000,0],[12000,8000],[0,8000]],"slope":30,"overhang":500}]),
    roof_extrusion: op("level,start,end,profile,depth", "type", M, [{"op":"roof_extrusion","level":"Level 2","start":[0,0],"end":[12000,0],"profile":[[0,0],[6000,3000],[12000,0]],"depth":8000}]),
    ceiling: op("level,points/from", "type,holes,offset", M, [{"op":"ceiling","level":"Level 1","points":[[0,0],[6000,0],[6000,4000],[0,4000]],"offset":2700}]),
    room: op("level,at/all", "name,number,department,allow_duplicate", M, [{"op":"room","level":"Level 1","all":true}, {"op":"room","level":"Level 1","at":[3000,2000],"name":"Office","number":"101"}]),
    room_separator: op("view,points", "closed", M, [{"op":"room_separator","view":"Level 1","points":[[6000,0],[6000,8000]]}]),
    area: op("view,at", "name,number", M, [{"op":"area","view":"Area Plan 1","at":[3000,2000],"name":"Zone A"}]),
    area_boundary: op("view,points", "closed", M, [{"op":"area_boundary","view":"Area Plan 1","points":[[0,0],[12000,0],[12000,8000],[0,8000]],"closed":true}]),
    opening: op("host,points/start+end", "offset,height", M, [{"op":"opening","host":"304601","start":[2000,0],"end":[3000,0],"offset":900,"height":1200}], { help: "Wall host: start/end are model XY points on the wall, offset is the sill height, height the opening height (default 2100). Floor/roof/ceiling host: points outline." }),
    shaft: op("level,top,points", "offset,top_offset", M, [{"op":"shaft","level":"Level 1","top":"Level 2","points":[[1000,1000],[2000,1000],[2000,2000],[1000,2000]]}]),
    ref_plane: op("start,end", "name,view", M, [{"op":"ref_plane","start":[0,-1000],"end":[0,9000],"name":"Axis A"}]),
    model_line: op("points", "level,line_style,closed,through", M, [{"op":"model_line","level":"Level 1","points":[[0,0],[5000,0],[5000,3000]]}]),
    stairs: op("level,top,points", "type,width,risers", meta(M, { idle: false, tx: "own" }), [{"op":"stairs","level":"Level 1","top":"Level 2","points":[[1000,1000],[1000,6000]],"width":1200}]),
    railing: op("points/host", "level,type", M, [{"op":"railing","level":"Level 1","points":[[0,0],[5000,0]]}, {"op":"railing","host":"305500"}]),
    curtain_grid: op("host,direction,positions/spacing", "mullion", M, [{"op":"curtain_grid","host":"305100","direction":"vertical","spacing":1500,"mullion":"Rectangular Mullion: 50 x 150mm"}]),
    toposolid: op("points", "type,level,survey", M, [{"op":"toposolid","points":[[-5000,-5000,0],[40000,-5000,0],[40000,30000,1500],[-5000,30000,1200]]}], { help: "z of each point is height above level when level is given, otherwise absolute." }),
  },
};
