// Catalog entry for `list` (SPEC Appendix A/B). The advertised part must stay equal to docs/design/SPEC-catalog.mjs
// unless the lead approves a surface change (e2e/budgets.json baseline). Lanes extend examples, help and errors.
import { B, E, meta, op, P, READ, RO_IDEM, S, SA, syn } from "../params.js";
import type { ToolSpec } from "../types.js";

const M = meta(READ);

export const tool: ToolSpec = {
  name: "list",
  title: "List model items",
  description: "List items of one kind (levels, views, sheets, schedules, rooms, types, families, materials, worksets, phases, links, revisions, filters, templates...) as compact rows. name= filters; for_element= valid types.",
  group: "read",
  annotations: RO_IDEM,
  discriminator: "kind",
  profiles: ["core", "full"],
  properties: {
    kind: syn(E(["levels","grids","views","sheets","schedules","rooms","areas","spaces","types","families","materials","worksets","phases","phase_filters","design_options","links","revisions","view_templates","view_filters","view_types","viewport_types","title_blocks","text_types","dimension_types","tag_types","line_styles","line_patterns","fill_patterns","scope_boxes","groups","systems","system_types","project_info","units"], "What to list."), {"level":"levels","grid":"grids","view":"views","sheet":"sheets","schedule":"schedules","room":"rooms","area":"areas","space":"spaces","type":"types","family":"families","material":"materials","workset":"worksets","phase":"phases","phasefilter":"phase_filters","designoption":"design_options","options":"design_options","link":"links","revision":"revisions","templates":"view_templates","viewtemplate":"view_templates","template":"view_templates","filters":"view_filters","viewfilter":"view_filters","filter":"view_filters","viewtype":"view_types","viewporttype":"viewport_types","titleblock":"title_blocks","textnotetypes":"text_types","texttype":"text_types","dimensiontype":"dimension_types","tagtype":"tag_types","tags":"tag_types","linestyle":"line_styles","linepattern":"line_patterns","fillpattern":"fill_patterns","scopebox":"scope_boxes","group":"groups","system":"systems","systemtype":"system_types","projectinformation":"project_info","unit":"units"}),
    name: S("Name contains (case-insensitive, * wildcard)."),
    category: P.category,
    level: S("Level name or id (rooms, areas, spaces, views)."),
    view_type: S("For views/view_types: FloorPlan, CeilingPlan, Section, Elevation, ThreeD, Drafting, Legend, AreaPlan, Sheet..."),
    family: S("For types: family name."),
    for_element: S("For types: element id; returns only types it can switch to."),
    placed: B("Views: on a sheet or not. Rooms/areas: placed or not."),
    graphical: B("Views: only graphical views (no schedules or browser-only views)."),
    printable: B("Views: only views that can be printed or exported."),
    class: S("Types: Revit API class, e.g. WallType, FloorType, FamilySymbol."),
    where: SA("Conditions 'Param op value' like find_elements."),
    ids: SA("Only these ids."),
    fields: P.fields,
    detail: P.detail,
    limit: P.limit,
    page: P.page,
    doc: P.doc,
  },
  required: ["kind"],
  ops: {
    levels: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"levels"}]),
    grids: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"grids"}]),
    views: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"views","view_type":"FloorPlan","placed":false}]),
    sheets: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"sheets"}]),
    schedules: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"schedules"}]),
    rooms: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"rooms","level":"Level 1"}]),
    areas: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"areas"}]),
    spaces: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"spaces","level":"Level 1"}]),
    types: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"types","category":["Doors"]}, {"kind":"types","for_element":"304512"}]),
    families: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"families","category":["Furniture"]}]),
    materials: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"materials","name":"concrete"}]),
    worksets: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"worksets"}]),
    phases: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"phases"}]),
    phase_filters: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"phase_filters"}]),
    design_options: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"design_options"}]),
    links: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"links"}]),
    revisions: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"revisions"}]),
    view_templates: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"view_templates"}]),
    view_filters: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"view_filters"}]),
    view_types: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"view_types","view_type":"Section"}]),
    viewport_types: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"viewport_types"}]),
    title_blocks: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"title_blocks"}]),
    text_types: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"text_types"}]),
    dimension_types: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"dimension_types"}]),
    tag_types: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"tag_types","category":["Door Tags"]}]),
    line_styles: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"line_styles"}]),
    line_patterns: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"line_patterns"}]),
    fill_patterns: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"fill_patterns"}]),
    scope_boxes: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"scope_boxes"}]),
    groups: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"groups"}]),
    systems: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"systems"}]),
    system_types: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", M, [{"kind":"system_types"}]),
    project_info: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", meta(M, { scope: "project" }), [{"kind":"project_info"}]),
    units: op("", "name,category,level,view_type,family,for_element,placed,graphical,printable,class,where,ids,fields,detail,limit,page,doc", meta(M, { scope: "project" }), [{"kind":"units"}]),
  },
};
