// Catalog entry for `modify_elements` (SPEC Appendix A/B). The advertised part must stay equal to docs/design/SPEC-catalog.mjs
// unless the lead approves a surface change (e2e/budgets.json baseline). Lanes extend examples, help and errors.
import { B, deg, E, I, meta, mm, N, op, P, PT, PTS, S, SA, syn, WD, WRITE, WRITE_TAIL } from "../params.js";
import type { ToolSpec } from "../types.js";

const M = meta(WRITE, { blast: ["bulk"] });

export const tool: ToolSpec = {
  name: "modify_elements",
  title: "Modify elements",
  description: "Edit existing elements chosen by ids, from= or filter=: move, copy, rotate, mirror, array, align, delete, pin, change_type, join/cut/attach, flip, split, reshape, group/ungroup. Deleting >20 asks to confirm.",
  group: "write",
  annotations: WD,
  discriminator: "op",
  profiles: ["core", "full"],
  properties: {
    ids: P.ids,
    from: P.from,
    filter: P.filter,
    by: P.by,
    to: mm(PT("Move/copy so the element's location point lands here [x,y(,z)] mm.")),
    levels: SA("copy: copy to these levels, aligned (vertical offset only)."),
    count: I("copy/array: number of copies (array includes original)."),
    angle: deg(N("Degrees counterclockwise (rotate, radial array).")),
    center: mm(PT("Rotation/radial center [x,y(,z)]. Default: element center.")),
    axis: PT("Rotation axis direction. Default [0,0,1]."),
    start: mm(PT("mirror: axis start; reshape: new curve start.")),
    end: mm(PT("mirror: axis end; reshape: new curve end.")),
    points: mm(PTS("reshape: new path for curve elements.")),
    through: mm(PT("reshape: point on arc.")),
    keep: B("mirror: keep original (mirror a copy). Default true."),
    kind: syn(E(["linear","radial"], "array: default linear."), {"line":"linear","lineararray":"linear","circular":"radial","polar":"radial","radialarray":"radial"}),
    target: S("align: grid, level, ref plane or element id to align to."),
    lock: B("align: lock the alignment."),
    with: S("join/cut/attach: the other element id or r# handle."),
    side: syn(E(["top","base","hand","facing","wall"], "attach/detach: top|base; flip: hand|facing|wall."), {"bottom":"base"}),
    at: mm(PT("split: split point; place_group: insertion point.")),
    type: P.type,
    pinned: B("pin: true pins (default), false unpins."),
    allow_pinned: B("Allow changing pinned elements."),
    expect_count: I("delete: abort unless exactly this many elements (incl. dependents) would be deleted."),
    expect_ids: SA("delete: abort unless the delete set (incl. dependents) is exactly these ids."),
    name: S("group/place_group: group name."),
    level: S("place_group: level."),
    ...WRITE_TAIL,
  },
  required: ["op"],
  ops: {
    move: op("ids/from/filter,by/to", "", M, [{"op":"move","from":"selection","by":[0,500]}]),
    copy: op("ids/from/filter,by/to/levels", "count", M, [{"op":"copy","ids":["304601"],"levels":["Level 2","Level 3"]}, {"op":"copy","ids":["304601"],"by":[0,3000],"count":3}]),
    rotate: op("ids/from/filter,angle", "center,axis", M, [{"op":"rotate","ids":["304601"],"angle":90}]),
    mirror: op("ids/from/filter,start,end", "keep", M, [{"op":"mirror","from":"r7","start":[6000,0],"end":[6000,8000]}]),
    array: op("ids/from/filter,count,by/angle", "center,kind", M, [{"op":"array","ids":["306000"],"count":5,"by":[1200,0]}]),
    align: op("ids,target", "lock", meta(M, { blast: [] }), [{"op":"align","ids":["304601"],"target":"A"}]),
    delete: op("ids/from/filter", "allow_pinned,expect_count,expect_ids", meta(M, { blast: ["delete"], inproc: false }), [{"op":"delete","filter":{"category":["Furniture"],"level":"Level 3"}}, {"op":"delete","ids":["304601","304602"]}], { help: "The delete set includes dependents; more than 20 returns NOT APPLIED with a confirm token. expect_ids aborts unless the delete set is exactly these ids." }),
    pin: op("ids/from/filter", "pinned", M, [{"op":"pin","from":"r3"}]),
    change_type: op("ids/from/filter,type", "", M, [{"op":"change_type","ids":["304601"],"type":"Basic Wall: Generic - 300mm"}]),
    join: op("ids,with", "", meta(M, { blast: [] }), [{"op":"join","ids":["304601"],"with":"305010"}]),
    unjoin: op("ids,with", "", meta(M, { blast: [] }), [{"op":"unjoin","ids":["304601"],"with":"305010"}]),
    switch_join: op("ids,with", "", meta(M, { blast: [] }), [{"op":"switch_join","ids":["304601"],"with":"305010"}]),
    cut: op("ids,with", "", meta(M, { blast: [] }), [{"op":"cut","ids":["305020"],"with":"304601"}]),
    uncut: op("ids,with", "", meta(M, { blast: [] }), [{"op":"uncut","ids":["305020"],"with":"304601"}]),
    attach: op("ids,with", "side", meta(M, { min: 2027, blast: [] }), [{"op":"attach","ids":["304601"],"with":"305300","side":"top"}]),
    detach: op("ids", "with,side", meta(M, { min: 2027, blast: [] }), [{"op":"detach","ids":["304601"],"side":"top"}]),
    flip: op("ids/from/filter,side", "", M, [{"op":"flip","ids":["306100"],"side":"hand"}]),
    split: op("ids,at", "", meta(M, { blast: [] }), [{"op":"split","ids":["304601"],"at":[6000,0]}], { help: "MEP curves break at the point; walls and framing are copied and trimmed. Inserts spanning the split point are refused." }),
    reshape: op("ids,start+end/points", "through", meta(M, { blast: [] }), [{"op":"reshape","ids":["304601"],"start":[0,0],"end":[10000,0]}]),
    group: op("ids/from/filter", "name", meta(M, { blast: [] }), [{"op":"group","from":"r7","name":"Bathroom A"}]),
    ungroup: op("ids/from", "", meta(M, { blast: [] }), [{"op":"ungroup","ids":["307000"]}]),
    place_group: op("name,at", "level", meta(M, { blast: ["create"] }), [{"op":"place_group","name":"Bathroom A","at":[20000,0],"level":"Level 2"}]),
  },
};
