// Transport error model and the D2 §11.4 mapping to catalog codes. Everything the broker generates without reaching
// the add-in is a BridgeResponse with ok=false, so tools handle broker- and add-in-side failures the same way.

import { BRIDGE_PROTOCOL_VERSION, type BridgeResponse } from "@revit-mcp-next/contracts/protocol";

export type TransportErrorCode =
  | "NOT_FOUND" //       ENOENT / ECONNREFUSED: the pipe does not exist (yet)
  | "BUSY" //            ETIMEDOUT / EBUSY / ERROR_PIPE_BUSY / own 3 s connect timer
  | "ACCESS_DENIED" //   EACCES / EPERM
  | "DISCONNECTED" //    close/end/EPIPE before a complete response
  | "TIMEOUT" //         the caller's wait ended
  | "ABORTED" //         the caller abandoned the exchange
  | "FRAME_TOO_LARGE" // response frame above 4 MiB
  | "BAD_RESPONSE" //    not a v3 response (parse error, wrong requestId, missing ok)
  | "REQUEST_TOO_LARGE";

export type TransportPhase = "connect" | "write" | "read";

export class TransportError extends Error {
  constructor(
    readonly code: TransportErrorCode,
    message: string,
    readonly phase: TransportPhase,
    /** The request frame was fully written, so the add-in may have received it. */
    readonly written: boolean,
    readonly errno?: string
  ) {
    super(message);
    this.name = "TransportError";
  }
}

export function isTransportError(error: unknown): error is TransportError {
  return error instanceof TransportError;
}

/** Map a socket errno seen before the request was written. */
export function classifyConnectErrno(errno: string | undefined): TransportErrorCode {
  switch (errno) {
    case "ENOENT":
    case "ECONNREFUSED":
    case "ENXIO":
      return "NOT_FOUND";
    case "EACCES":
    case "EPERM":
      return "ACCESS_DENIED";
    case "ETIMEDOUT":
    case "EBUSY":
    case "ERROR_PIPE_BUSY":
    case "EAGAIN":
      return "BUSY";
    default:
      return "DISCONNECTED";
  }
}

/** A failure envelope generated by the broker (never reached or never answered by the add-in). */
export function failure(requestId: string, code: string, message: string, details: Record<string, unknown> | null = null): BridgeResponse {
  return { v: BRIDGE_PROTOCOL_VERSION, requestId, ok: false, code, message, details };
}

export function isFailure(response: BridgeResponse | null | undefined, code?: string): boolean {
  return !!response && response.ok === false && (code === undefined || response.code === code);
}
